version: "3.1"
services:
  nies:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: nepolin/players_api_dev
    volumes:
      - $PWD:/workdir
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nepolin/players_api
    ports:
      - "6969:80"
    volumes:
      - $PWD:/workdir