FROM python:3
WORKDIR /workdir
COPY . .
RUN pip install --upgrade pip && pip install \
    black \
    flake8 \
    git+https://github.com/niesfutbol/players_from_as.git \
    mutmut \
    mypy \
    pandas-stubs \
    pylint \
    pytest \
    pytest-cov
COPY ./app /app
